### ISSUE TITLE
Regex pattern in "orig_id" does not validate in Java

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#102]
Suggested regex change would be "^(?!OEB).+" instead of "^(?!(?i)OEB)"

**Comment by jmfernandez** [comment]
Thanks, @vsundesha and @redmitry , triaging the issue. The main problem is that some regex implementations were considering the original regex as an empty one, because it had only the negative match pattern. I have just added fixes in 5d879f911d0a5e00a986a8c2d8a7343515212700 , so it works on any implementation (hopefully)
