### ISSUE TITLE
Structure of the implementations field in the Metrics Schema

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#104]
The implementations field currently holds 2 properties, tool_id which is a string and community_ids which is an array, we think that it should be inverted, the community_id should hold a String and the tool_ids should hold an array, because a metric might be applied to several tools in the same community.

**Comment by jmfernandez** [comment]
The issue you have just opened is a bit confusing, because **Metrics**._implementations_ contains the list of implementations of this metric, i.e. the list of registered programs (i.e **Tool** entries) whose code compute this kind of metric, used by one or more communities registered as **Community** entries

**Comment by jmfernandez** [comment]
With the changes from e3bc8d0 , 93a43ab and 2400ae6, this issue does not make sense
