### ISSUE TITLE
Tool types

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#108]
After checking the list in the 'participants' tab here: https://openebench.bsc.es/html/scientific/OEBC001
we realized that currently we have no way to differentiate between the different tools, that is, benchmark participants are listed together with metrics computation/aggregation tools. 
Would it be useful to have a specific attribute for this? I guess it would not break anything we already have?
Could be something like:
type: enum [participant, metrics_computation, ... , other]
That way we would be able to show them separately, or hide them depending on the user role.

**Comment by jmfernandez** [comment]
The role a `Tool` is playing always depends on the _`action_type`_ of the `TestAction` entry which refers it, so you have to derive the list of tool ids from the `TestAction` entries whose _`action_type`_ is **`TestEvent`** .

Predefining the tool's role could have implications, because there could be a challenge to evaluate different kinds of tools implementing metrics (the referred tools are from challenge participants, so the `TestAction` will have as _`action_type`_ **`TestEvent`**), and once the most promising ones are chosen by the community, use those tools implementing as such (the referred tools are computing the metrics of the challenge, so the `TestAction` will have as _`action_type`_ **`MetricsEvent`**)
