### ISSUE TITLE
Dataset suggestions

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#12]
Dataset (type: Rreference): the same datasets without the results, and additional datalinks to the data (in this case: reference sequence and experimental pdb). ReferenceDatasets could be reused in other benchmarking events, or accessed and used offline by developers, etc. Should contain all the information to repeat the test. 
-Dataset (type: EventInput): Simple collection of reference Datasets used in a given BenchmarkingEvent (1 week in this case).  It is usual that input on Events are collections of targets.  This can be a specific Dataset but also can be obtained from the TestEvents associated to the BenchEvent, however this list should be known before making the tests. 
-Dataset (type: Output): Output of the TestEvents.  If tools’ output is available could be rescored as new metrics appear or metrics are modified. It relates to a reference + tool + testEvent. The global output dataset for a give Event is a collection of output datasets referred by its testEvents. Of course these can be kept private.  
-Dataset (type:metrics_report): Aggregated Metrics results as available on present datasets.  Report datasets may have structures specific to the metric or community. 

In this way the cycle would be:
1.	The community defines one or more reference Datasets
2.	The community defines one or more Metrics (specification in a way that can be executed, reference to a container or VM somewhere, just descriptions)

1 and 2 are dependent only on the Community and can be “used” in one or more events. 

3.	A BenchmarkingEvent is planned. This includes some Dates, urls, docs, etc and a Collection of ReferenceDatasets (Dataset: EventInput)
4.	Participants  in the BenchmarkingEvent  (or the appropriate daemon) submit TestEvents (a reference Dataset + Tool -> Output). TestEvent are single executions (the same tool and reference with different settings give a different one, and so several replicated executions for instance). Details of the execution should be available in the TestEvent. 
5.	Metrics are applied to the Output of the submitted testEvents and one or more ReportDatasets are generated. “Applied” is very general.  “Metrics” could include manual assessments, etc.  ReportDatasets can be per Tool (these would go to bio.tools eventually), per Event, aggregated on time, etc.  These can be associated to the Event or to the Community (annual summaries, for instance).

**Comment by diglesia** [comment]
I totally agree with the distribution of the different types of datasets. We should apply these changes to the data model (v0.4):
In the case of Quest for Orhologs, we will have:
- Dataset - Input: Reference proteome in FASTA and OrthoXML formats. 
- Dataset - Output: Orthologs predictions that could be provided as pairwise orthologs or as trees.
- Dataset - Metrics report (or Results): Aggregated results for metrics (quantitative results that can include code to generate the corresponding plots). 
We should also include the final ranking of tools in the BenchmarkingEvent, obtained after applying the metrics to the outputs and selecting the best performers.
--------------------------
(1 and 2) The community defines the reference datasets and the metrics but I am not sure if these elements (at least the reference datasets) should be linked directly to the BenchmarkingEvent (instead to the Community): reference datasets are not usually reused from one event to another, since these datasets are updated frequently, and scientific questions may also change a lot between events. I think they could be better attached to the BenchmarkingEvent and indirectly related to the Community through the BenchmarkingEvent.
(3, 4 and 5) I agree with the definition of the different elements related to a BenchmarkingEvent. I think Metrics Report datasets should be per tool and event (in order to facilitate the ranking generation) and then we can generate results aggregated  on time and summaries for the Community.

**Comment by jlgelpi** [comment]
Reference Datasets linked to the Community. I was thinking in datasets that can be used by developers for day-to-day tests, They can be used in one or more (probably not) or never used in any actual Event. For instance CAPRI people uses a well known and periodically updated reference dataset. Part of it is used in CAPRI events but the whole dataset is there as reference for developers. This is very match in the line of "Datasets" as considered by the Interoperability platform.

**Comment by diglesia** [comment]
OK, I did not consider such case and it makes sense. Thank you for the clarification.

**Comment by jlgelpi** [comment]
(5) I would be very open in the options for reports. CAMEO uses an integrated report per Event (with all tools together), Others have separate reports by tool and event, and some aggregated reports could be done on the fly, but others could be too complex and should stored in the DB. NoSql es very flexible on that.

**Comment by diglesia** [comment]
OK, we can define the result reports case by case and then decide what should be included in the data model.

**Comment by diglesia** [comment]
We will keep the "generic" approach for v0.3.x, having a general Dataset type which includes all types of dataset (input, output, results).
For v0.4.x, we will discuss how to represent the different types of datasets. We should analyze in depth the results report provided by the different communities for each benchmarking event, case by case.

**Comment by jmfernandez** [comment]
Done in commits 93a09ff3f9f5e7e6ada9c03e730aec05ccf70578 , 1c6121e4e8318ceb0d47618bc212ae978f7e81e3 and 25e4508ecd4377b769daaef2e00e2bfb64240f43
