### ISSUE TITLE
Shall we provide an special case for a "dummy" participant/resource?

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#19]
It would be good - I think - if we offer to the organizers the possibility of testing metrics, submissions, etc; having a dummy profile which look like a participant/resource but it will never ever show up in the summary.

**Comment by jlgelpi** [comment]
Agree. We didn't have defined what a "participant" is, only the contact. Should we define "participant types"?
Alternatively we can mark testEvents as "test" or "debug", so they are not considered in aggregated reports.

**Comment by diglesia** [comment]
Agree, but we should decide what to do with the data generated from such tests: would we offer the participant the possibility to store the generated data for further comparison with other dummy tests? If so, some participants (for instance, those following a trial-and-error approach) could generate tons of data. 
On the other hand, I think we should mark these testEvents as "test" instead of defining a "participant", maintaining the current (implicit) correspondence between "tool" and "participant" to keep the data model as simple as possible (and as non-relational as possible).

**Comment by diglesia** [comment]
In testEvent, we will include a field (Enum type) to define the type of event: test, debug, final, etc.

**Comment by jmfernandez** [comment]
I think that, if this attribute appears, it should not be included in the aggregated results

**Comment by jmfernandez** [comment]
I have followed a different approach. With the changes in 6f7a0ce4a5c7fdf2be5e1c2d99b70e4a8c31c1a1 the official participants are properly attached ti the `benchmarkingEvent`, and the associated `testEvent` identified. But we can still create "unofficial" or "orphaned" `testEvents` linked to the `benchmarkingEvent`. In order to identify who requested/owns it, test_contact_ids has been added through commit 1eece57e946a1171f7d27e47980a3f858daa2caa

(Hopefully this issue is closed with this)
