### ISSUE TITLE
Add label attribute to some schemas

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#72]
Following the changes in issue #66, we have completely removed meaning from the identifiers. However, we are missing some information in some schemas by doing so (specially in Challenges, Datasets, Metrics and TestActions). 
I would suggest creating a 'label / short_id / abbreviation' attribute to those schemas, kind of an acronym which indicates what it is found in that schema (like an internal id). For now, this only exists in the Community.

If we want to go one step further we can even think of some kind of hierarchy, so that, for instance, in a dataset, we can identify which challenge and tool the it belongs to, without having to call the API twice.

Some examples: 

<table style="width:100%" align="center">
  <tr>
    <th>Schema</th>
    <th>Quest for Orthologs</th>
    <th>Cancer Genome Atlas</th>
  </tr>
  <tr>
    <th>Community</th>
    <td>QfO</td>
    <td>TCGA</td>
  </tr>
 <tr>
    <th>Challenge</th>
    <td>STD <i>(Species Tree Discordance Test)</i></td>
    <td>BRCA <i>(Breast Invasive Carcinoma)</i></td>
  </tr>
 <tr>
    <th>Metrics</th>
    <td>RF-dist <i>(Robinson-Foulds distance)</i></td>
    <td>TPR <i>(True Positive Rate)</i></td>
  </tr>
<tr>
    <th>TestAction</th>
    <td>STD:PhylomeDB:testEvent</td>
    <td>BRCA:e-Driver:metricsEvent</td>
  </tr>
<tr>
    <th>Dataset</th>
    <td>STD:PhylomeDB:participant</td>
    <td>BRCA:e-Driver:assessment</td>
  </tr>

</table>

**Comment by jlgelpi** [comment]
I would use this for identifiers that come from the community. If these are for recovering the old schema, I would prefer to complete the schema with the fields that may be missing ( much easier to browse as field than in a single string). Otherwise this would finally recover the mess that we were trying to avoid -)

**Comment by javi-gv94** [comment]
Then we could keep a label attribute in the Community, Challenge and Metrics; as those acronyms usually come from the community.
Regarding the TestActions and Datasets, maybe we could include that label next to a pointer to a Challenge/Tool/Community every time it is used. I guess that wouldn't be that messy. See example file:
/home/jgarrayo/benchmark_repositories/example_participant_dataset.json

**Comment by jlgelpi** [comment]
In general, when any piece of data has an id or label that comes from the Community it should be stored in the corresponding document. There is no need to repeat them in any reference as they are stored in the main entry, since labels can be obtained easily. I.e. Datasets come from Challenges, we would have the challenge id (OPBC....) and in the Challenge document keep everything that is needed. Repeating labels on each reference generates a probable source of inconsistencies, in the case that label is changed or updated.

**Comment by JuergenHaasSIB** [comment]
these are non-binding properties:
auto-generate labels (aids data filtering/retrieval) and store them vs auto-generate on-the-fly (annotation for human readability)

**Comment by jmfernandez** [comment]
Fixed in commit 07469a78ced081ca3eeb9d59c5af079f87f3b37d , where attribute `orig_id` is added to several concepts
